import torch

BATCH_SIZE = 64
BLOCK_SIZE = 64
MAX_ITERATIONS = 5000
EVALUATION_INTERVAL = 500
LEARNING_RATE = 3e-4
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
EVALUATION_ITERATIONS = 200
NUM_EMBEDDING_DIMENSIONS = 2
NUM_HEADS = 2
NUM_LAYERS = 2
DROPOUT = 0.2
MAX_NEW_TOKENS = 500

torch.manual_seed(1337)