import torch

BATCH_SIZE = 64
BLOCK_SIZE = 256
MAX_ITERATIONS = 5000
EVALUATION_INTERVAL = 500
LEARNING_RATE = 3e-4
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
EVALUATION_ITERATIONS = 200
NUM_EMBEDDING_DIMENSIONS = 384
NUM_HEADS = 6
NUM_LAYERS = 6
DROPOUT = 0.2

torch.manual_seed(1337)